name: Build and Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore ./Banana.sln
    
    - name: Build
      run: dotnet build ./Banana.sln --configuration Release --no-restore
    
    - name: Test with coverage
      run: dotnet test ./Banana.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
    
    - name: Upload test results
      uses: actions/upload-artifact@v2 
      if: always()
      with:
        name: test-results
        path: "**/TestResults/**/*"
        retention-days: 7
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: coverage-report
        path: "**/TestResults/**/coverage.cobertura.xml"
        retention-days: 7
